### ISSUE TITLE
Add some readme

### ISSUE THREAD

**Issue by romitkarmakar** [node-casbin/hapi-authz#1]
Could you add atleast a readme file so that I can fork this repo and add my code into it.

**Comment by nodece** [comment]
You can see the https://github.com/node-casbin/express-authz.

**Comment by romitkarmakar** [comment]
@nodece  I have developed the hapi-authz middleware. Check this link: https://github.com/romitkarmakar/hapi-authz . Just wanted to transfer this repository to this organisation.

**Comment by nodece** [comment]
@romitkarmakar
 Can you make it support TypeScript? 
We should allow users to customize the `register`.

**Comment by nodece** [comment]
@romitkarmakar  Please refer to https://github.com/node-casbin/koa-authz#use-a-customized-authorizer.

**Comment by romitkarmakar** [comment]
@nodece , Thanks for you suggestion. I will migrate it to Typescript and allow user to customise the register.

**Comment by romitkarmakar** [comment]
@nodece migration to typescript and custom authorization class support has been done.

**Comment by nodece** [comment]
@romitkarmakar good. Can you make a PR to the repo?

**Comment by romitkarmakar** [comment]
@nodece  I cannot fork this repo currently, as github is showing 

> Cannot fork beacuse repository is empty.  

Please add some readme, so that I will be able to fork this repo.

**Comment by nodece** [comment]
Yeah, done.
