### ISSUE TITLE
Is this lib ready? Can we add badges (CI, code coverage, NPM, etc.) and push it to NPM?

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/hapi-authz#4]

**Comment by hsluoyz** [comment]
@nodece @romitkarmakar can anyone help on this?

**Comment by stu01509** [comment]
Hi @hsluoyz 

I am interested in this issue can you assign to me?

**Comment by nodece** [comment]
@stu01509 This lib has been released to NPM, could you add badges?

**Comment by hsluoyz** [comment]
https://www.npmjs.com/package/@casbin/hapi-authz

**Comment by stu01509** [comment]
@nodece Sure, I will follow the current repo to do that.

**Comment by hsluoyz** [comment]
@stu01509 

1. Please consider switch to GitHub Actions from Travis CI.
2. Please mirror the NPM releases: https://www.npmjs.com/package/@casbin/hapi-authz to GitHub Releases: https://github.com/node-casbin/hapi-authz/releases

**Comment by stu01509** [comment]
@hsluoyz 

I add the first release version to GitHub, please take a look.

**Comment by hsluoyz** [comment]
You should have done it like this: https://github.com/node-casbin/hapi-authz/releases
